baseURL = ""
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
theme = ["github.com/onweru/compose"]
title = "Compose Docs"
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
style = "monokai"
tabWidth = 2
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[[menu.main]]
name = "Docs"
url = "docs/"
weight = 2
[[menu.main]]
name = "Example"
url = "https://docs.neuralvibes.com"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
codeLineNumbers = false
codeMaxLines = 7
enableDarkMode = true
repo = "https://github.com/notnoobdude/compose"
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
[params.author]
name = "Weru"
url = "https://neuralvibes.com/author/"
[params.logo]
darkMode = "images/compose-light.svg"
lightMode = "images/compose.svg"
[params.source]
iconDark = "images/GitHubMarkDark.svg"
iconLight = "images/GitHubMarkLight.svg"
name = "GitHub"
url = "https://github.com/onweru/compose/"
