[build]
publish = "public"
#command = "hugo --gc --minify"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.79.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.79.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.79.1"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.79.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
